; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stick-c-plus2]
platform = espressif32@6.7.0
board = m5stick-c
board_build.filesystem = littlefs
framework = arduino

upload_speed = 1500000
monitor_speed = 115200 ;文字化け対策
monitor_after_upload = false   ; ←自動モニタを明示的にOFF（OK）
monitor_filters = printable

board_build.partitions = huge_app.csv

; シリアルポートの自動選択を有効化
;upload_port = COM4
;monitor_port = COM4

build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=5

lib_deps =
  M5Unified=https://github.com/m5stack/M5Unified
  mikalhart/TinyGPSPlus
  tzapu/WiFiManager

